### ISSUE TITLE
LaTeX Error: File `./logos/jku_k_black' not found when package is installed to local TEXMF directory

### ISSUE THREAD

**Issue by hpretl** [michaelroland/jku-templates-presentation-latex#3]
I installed the package into `texmf-local` directory, and the above error shows up. Is something wrong with my install (I am using TexLive 2023 on a *nix system) or something in the package?

**Comment by michaelroland** [comment]
To be honest, I haven't thought about installing the package. It was rather intended to be placed into each TeX project it is used for. Not sure what would need to be done to load resources like logos and fonts from an installation directory. Ideas are welcome though ...

**Comment by hpretl** [comment]
With this change it works:
```
diff --git a/beamerthemejku.sty b/beamerthemejku.sty
index 3659229..3f38ae5 100644
--- a/beamerthemejku.sty
+++ b/beamerthemejku.sty
@@ -44,7 +44,7 @@
 %%

 % Option logopath={}: set path to template logo resources (defaults to "./logos")
-\newcommand{\jkubeamer@logopath}{./logos}
+\newcommand{\jkubeamer@logopath}{logos}
 \DeclareOptionBeamer{logopath}{\renewcommand{\jkubeamer@logopath}{#1}}

 % Option [no]frametitlecaps: set frame titles in all-caps (defaults to false)
```

**Comment by hpretl** [comment]
I can make a PR if needed :-)

**Comment by hpretl** [comment]
Yes, `pdflatex`.

**Comment by hpretl** [comment]
I quickly tested with `xelatex`: Removing the `./` does not work, but a fully qualified path works. However, that would need customization by every user.

**Comment by michaelroland** [comment]
Feel free to open a PR for the logo folder part.

**Comment by michaelroland** [comment]
Done. @hpretl can you confirm that #4 works for you?

**Comment by hpretl** [comment]
@michaelroland Yes, this works beautifully for `pdflatex`, and also `xelatex` if the fonts are installed into the proper directory as stated by the warning that pops up.
