### ISSUE TITLE
Logos not found

### ISSUE THREAD

**Issue by hpretl** [michaelroland/jku-templates-presentation-latex#6]
Where do I have to put logos that I want to use with `\institutecode{code}` or `\partnerlogo{filename}`? So far I tried different things, but no success.

Which file formats are supported?

**Comment by michaelroland** [comment]
### For `\institutecode{code}`

The logo should be in the logo path (either `logos/` in current directory, the logos path in your package installation (as in #4) or whatever you set as logopath with the package option). The files should be named
- `jku_code_black.pdf`: Intitute logo in black with text below
- `jku_code_black_wide.pdf`: Institute logo in black with text on right side
- `jku_code_color.pdf`: Institute logo in faculty color
- `jku_code_white.pdf`: Institute logo in white
See the existing `jku_LIT_*.pdf` logos for an example. Other file extensions/formats besides `.pdf` are supported (whatever the graphicx package provides).

### For `\partnerlogo{filename}`

Filename is searched in the input path, e.g. `./partnerlogo` uses `partnerlogo.pdf` (or `partnerlogo.png` or whatever) from the same path as `main.tex`. Omitting the leading `./` would also allow you to search in the whole input path (including package resources). If you use `\partnerlogo{./partnerlogo}`, you should actually provide two files:
- `partnerlogo.pdf`: For use on light background
- `partnerlogo_white.pdf`: For use on dark background
You can change the `partnerlogo_white.pdf` to any other filename by using `\partnerlogo[white=./otherlogo.png]{./partnerlogo.pdf}`.

You may also use `\footerpartnerlogo{filename}` to set a separate logo for use in footers (then `\partnerlogo{}` will be used for title slides only).

**Comment by hpretl** [comment]
Thank you, that clarifies it!
