### ISSUE TITLE
Pandoc (Markdown - Latex) Support

### ISSUE THREAD

**Issue by michaelk99** [michaelroland/jku-templates-presentation-latex#7]
# What and Why
I like to use *pandoc* to generate nice beamer slides from a markdown file
`pandoc -t beamer pres.md -o pres.pdf`

Unfortunately, this jku beamer theme does not work out-of-the box.
I've setup my tex installation so that the jku beamer template on the respective path and this works with normal latex beamer slides.

# Example 
See the attached file [pres.md](https://github.com/michaelroland/jku-templates-presentation-latex/files/14507818/pres.md)
If `theme: Boadilla` is selected the file `pres.pdf` is generated without errors.
[pres.pdf](https://github.com/michaelroland/jku-templates-presentation-latex/files/14507819/pres.pdf)

# Error
When I set the JKU theme in the Markdown file `theme: jku`, I get the following error:

>Error producing PDF.
>! LaTeX Error: \begin{itemize} on input line 146 ended by \end{beamer@framepauses}.
>
>See the LaTeX manual or LaTeX Companion for explanation.
>Type  H <return>  for immediate help.
> ...                                              
>                                                  
>l.146 
>
> \end{frame}

**Comment by michaelk99** [comment]
Thanks for the quick fix and the detailed pandoc preamble! Works as expected!

**Comment by michaelroland** [comment]
Btw. for the full design experience of the template, you may want to compile using the XeLaTeX toolchain with
```
pandoc -t beamer --slide-level=3 --pdf-engine=latexmk --pdf-engine-opt=-gg --pdf-engine-opt=-bibtex --pdf-engine-opt=-pdfxe main.md -o main.pdf
```
or
```sh
pandoc -t beamer --slide-level=3 --pdf-engine=xelatex main.md -o main.pdf
```

Use `--slide-level=N` to determine the heading level that will produce frames in case you want sectioning (with `--slide-level=3`, level 1 headings will produces section slides, level 2 headings subsection slides, and level 3 headings will produce frame titles)

**Comment by michaelk99** [comment]
Thanks! I'll give it a try!

**Comment by michaelroland** [comment]
Do you have some longer source file with typical pandoc/markdown features that you use in your projects? Would be interesting as a test-case ...

**Comment by michaelk99** [comment]
I mainly use it as a quick way to produce slides for meetings based on some notes. So mainly some images and Latex equations. Need to look into setting up the bibliography.

**Comment by jondo** [comment]
Here's a small example (adapted from [here](https://ashwinschronicles.github.io/beamer-slides-using-markdown-and-pandoc)), showing the following features: list, enumeration, web link, bibliographic reference,  image, equation, table.

[markdown-slides.zip](https://github.com/user-attachments/files/16107159/markdown-slides.zip)
