### ISSUE TITLE
Missing character for `\implies`

### ISSUE THREAD

**Issue by jondo** [michaelroland/jku-templates-presentation-latex#9]
`\implies` yields: `[WARNING] Missing character: There is no ⟹ (U+27F9) (U+27F9) in font [fonts/PublicSans-Regular.ttf`, similar with `\Rightarrow`.

A glyph-not-found character is displayed instead.

Seen with commit 2893dde89bf85ca954d95ef0fab6cf11faabd3a2.

**Comment by michaelroland** [comment]
Unfortunately, I can't reproduce this issue. For me, `$a \implies b$` ($a \implies b$) and `$a \Rightarrow b$` ($a \Rightarrow b$) works just fine. Tested with and without mathastext / eulermath options.

Did you try to use `\implies` or `\Rightarrow` outside math mode? This is not supported as Public Sans does not ship the necessary unicode characters.

**Comment by jondo** [comment]
Thank you for the help – yes, it was my mistake to use it outside math mode!
